name: ci-workflow.yml # 워크플로를 구분하기 위한 이름

on: # 이벤트 핸들러
  pull_request:
    branches:
      - 1-비상비상
      - main
jobs:
  code-test:
    name: 코드 테스트
    runs-on: ubuntu-latest

    steps:
      - name: 브렌치로 체크아웃
        uses: actions/checkout@v6

      - name: 자바 설치
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: 25

      - name: gradlew 권한 설정
        run: chmod +x ./gradlew

      - name: 테스트 실행
        run: ./gradlew test --no-daemon
